### ISSUE TITLE
Strip out unused constructors in PIR

### ISSUE THREAD

**Issue by michaelpj** [IntersectMBO/plutus#4148]
We can do whole-program analysis, so we can actually remove constructors from datatypes that are unused. 

------------

Example (in pseudo-PIR):
```
let datatype (Maybe :: Type -> Type) [a :: Type] match_Maybe [Just :: a -> Maybe a, Nothing :: Maybe a]
     f = \(x :: Maybe Integer) -> match_Maybe x (\(y :: Integer) -> y) 0
in f (Just 1)
```
Since the `Nothing` constructor is never used, we can get rid of it! We then have to get rid of the corresponding arguments to `match_Maybe` everywhere too:
```
let datatype (Maybe :: Type -> Type) [a :: Type] match_Maybe [Just :: a -> Maybe a]
     f = \(x :: Maybe Integer) -> match_Maybe x (\(y :: Integer) -> y)
in f (Just 1)
```

-------------

This should mostly work with the dead-code analysis as is. Currently it over-approximates the dependencies between parts of a datatype (we assume they all depend on each other, which isn't true). If we fix that, we should naturally find out which constructors are dead.

Removing them would be more complicated because of the need to also remove the case branches throughout the rest of the program.

**Comment by kk-hainq** [comment]
> I have only one idea for making this a bit safer in the future, which is to make applyCode apply pre-optimized PIR programs, not erased PLC programs.

Wouldn't this require storing PIR programs on-chain? I would love to do most optimizations at the PIR level, but this seems to go against the desired goal of smaller on-chain scripts.

In case #458 dies horribly or becomes very hard to navigate, I'll port my comment there here:
> I think we will have to go with an "incorrect" dependency to be useful for Cardano validator scripts. A "correct" one would just nuke validator scripts as unused functions. Making deconstructors depend on constructors was very dumb (I now think deconstructors do not need to depend on anything?), but there may still be helpful rules. For example, if a program reduces to a function, all of its type arguments (and their type dependencies?) must stay intact, while other types in the program can still be truncated. Another ambitious effort might be truncating input types (like `ScriptContext`) only to keep fields used by the validator script. A node would then have to parse each script to truncate the input values correspondingly (If that even makes sense...).

**Comment by kk-hainq** [comment]
@michaelpj Sorry it was yet another late-night drunk dumb comment. I literally worked on lifting and benchmarked `applyCode`ed example contracts on this task and somehow still misunderstood it...

In retrospect, that idea with your comment on the PR should be enough for me to continue this work.

> A validator
> 
> ``` haskell
> myValidator :: MyDatum -> MyRedeemer -> ScriptContext -> Bool
> myValidator = ...
> ```
> is actually wrapped up with conversions from Data, so in fact it's something like:
> 
> ``` haskell
> myValidator' :: Data -> Data -> Data -> ()
> myValidator' d r c = myValidator (unsafeFromData d) (unsafeFromData r) (unsafeFromData c)
> ```
> 
> So we do have references to all the pieces of the types in question due to the IsData instances. It's only Data that looks unused - but it's a builtin type.

I'll do the saner directions first, then hopefully revisit this in the future.
> 
> So I think we could get away with it, although it's still a bit questionable.

**Comment by rjmh** [comment]
> > We can do whole-program analysis
> 
> Note that this is only true if we really do have the whole program, which means the user must _not_ apply the optimized program to something else. In particular, they must not use the common pattern of making an parameterized validator by compiling a function and applying it to a separately-constructed argument, e.g.
> 
> ```
> $$(complile [|| \(x :: Maybe Int) -> case x of {Just x -> x; Nothing -> 0} ||]) `applyCode` Lift.liftCode (Just 1)
> ```
> 
> will go badly if we strip out the constructors of `Maybe` in the function!
> 

But this case is easy to recognise: Maybe occurs in the type of the term being compiled, and so it's representation cannot be changed without changing the meaning of the compiled code. You should be able to strip unused constructors from *other* types without a problem.

This would mean there might be dead constructors in the result of applyCode, but I don't think that is really a problem.

**Comment by michaelpj** [comment]
> But this case is easy to recognise: Maybe occurs in the type of the term being compiled, and so its representation cannot be changed without changing the meaning of the compiled code. You should be able to strip unused constructors from other types without a problem.

Interesting idea. Obviously it would have to be all types that are transitively used by the type of the final term, but that would make things better indeed.

**Comment by kk-hainq** [comment]
> But this case is easy to recognise: Maybe occurs in the type of the term being compiled, and so its representation cannot be changed without changing the meaning of the compiled code. You should be able to strip unused constructors from other types without a problem.

To safely modify types for cross-program application the types must be unused, or only used at the type level. In such a case, we can replace then eventually remove it per #4147, instead of just finding unused constructors to remove!

**Comment by effectfully** [comment]
@michaelpj what's the status of this issue?

Since it's a non-critically-important optimization, for the time being I'm marking it with "Low priority".

**Comment by michaelpj** [comment]
Yeah, I think that's right. It's also a bit tricky.

**Comment by effectfully** [comment]
Rereading through that issue, @michaelpj can we consider this one done?

**Comment by michaelpj** [comment]
Sure
