### ISSUE TITLE
[Plutus] Filter out combined-plutus-haddock, and read-the-docs-site from the non-x86_64-linux builders.

### ISSUE THREAD

**Issue by angerman** [IntersectMBO/plutus#5302]
They don't need to be build anywhere outside of x86_64-linux, and take a long time (up to timeout), thus producing contention and blocking other jobs.

**Comment by effectfully** [comment]
@zeme-iohk could you please take a look at this issue and say what you think?

**Comment by effectfully** [comment]
Asked Lorenzo privately, he told me the issue got done somewhere along the way, hence closing.
