### ISSUE TITLE
Error upon fresh import of plutus-metatheory into Agda project

### ISSUE THREAD

**Issue by lemmon-714** [IntersectMBO/plutus#5735]
### Summary

Tried to use the UPLC agda from the metatheory and it failed at import.

### Steps to reproduce the behavior

1. clone plutus repo
2. add `name: Plutus` to plutus-metatheory/Plutus.agda-lib
3. add absolute path to Plutus.agda-lib to agda libraries file
4. clone [stand](https://github.com/agda/agda-stdlib) 
5. add absolute path to standard-libary.agda-lib to agda libraries file
6. note that the `name` of the lib inside the agda-lib file is actually `standard-library-2.1`
7. create agda defaults file and add `standard-library` to it
8. create a new Agda project with the agda-lib file containing
```
include: src
depend: Plutus
```
9. create a new file src/HelloProof.agda containing
```
open import Agda.Primitive
open import Untyped.CEK

data _≡_ {a} {A : Set a} (x : A) : A → Set a where
  refl : x ≡ x

reflexive : {A : Set} {x : A} → x ≡ x
reflexive = refl
```
EDIT: commenting out everything but `import Untyped.CEK` didn't change the outcome.
10.  run agda on that file using vscode with the agda-mode extension

### Actual Result

```
(...)/plutus/plutus-metatheory/src/Utils/List.lagda.md:109,47-110,79
_i_213 ≡ _k_215 !=< List A
when checking that the inferred type of an application
  _i_213 ≡ _k_215
matches the expected type
  List A
```

### Expected Result

`*All Done*`

### System info

OS: MacOS Sonoma
Plutus (tried multiples with identical result):
- commit @d1ef450 (latest)
- tag 1.20.0.0
- commit @ec781723

**Comment by michaelpj** [comment]
We are building against version 1.7.3 of the stdlib, so it seems unlikely that it will work with version 2.1.

**Comment by lemmon-714** [comment]
Thank you, that worked!
