### ISSUE TITLE
You told me to report this so here it is

### ISSUE THREAD

**Issue by jonathanfishbein1** [IntersectMBO/plutus#5770]
### Summary

Error: submit tx failed: ErrorSubmitTx.failed.(400)
failed:
aab3e076a3d3c29ada4cbac924937b5da7420fd1ea202caba0ce44dff88c1a47
Whoopsie, the ledger failed to upgrade an data-type from an earlier era into data of a newer era. If you ever run into this, please report the issue as you've likely discoverd a critical bug...

### Steps to reproduce the behavior

asdfasdf

### Actual Result

asfdasdf

### Expected Result

asdfasdf

### System info

NixOS
Brave

**Comment by zliu41** [comment]
The error is from ogmios -> https://github.com/CardanoSolutions/ogmios/issues/368
