### ISSUE TITLE
Getting the validator hash onchain

### ISSUE THREAD

**Issue by Fiftyw3bs** [IntersectMBO/plutus#5778]
I've just discovered that there are no more `ownHash` or `ownHashes` in the `PlutusLedgerApi.V2.Contexts`. How else can a validator access its own hash?

**Comment by zliu41** [comment]
`ownHash` is just a helper function. The `plutus-ledger-api` package is supposed to contain types and functions required by the ledger; `ownHash` isn't one of them, so it was removed. The own hash is still available in `ScriptContext`, from the `txOutAddress` field.

**Comment by effectfully** [comment]
The issue seems resolved to me, so I'm closing it. Do feel free to reopen if you disagree.
