### ISSUE TITLE
Create an efficient drop-in Data replacement for AssocMap.Map

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#5929]
From @zliu41 :

AsData doc: https://github.com/IntersectMBO/plutus/pull/5729 

The goal is to create a Map for Plutus Tx that is encoded in BuiltinData. In contrast, PlutusTx.AssocMap wraps a regular list encoded in SOP.

Using AsData on PlutusTx.AssocMap won’t be effective, because it is backed by a regular (SOP-encoded) list, not a data-encoded list. If we simply wrap the PlutusTx.AssocMap.Map definition in AsData, it would become less, not more efficient, because two frequent operations, wrapping and unwrapping (via toList and fromList ) will be linear (converting an SOP list to or from Data).

Instead, we should implement all operations for the new Map type such that they do not involve regular lists.

I have an initial implementation but didn’t finish addressing all the comments: https://github.com/IntersectMBO/plutus/pull/5701 Please take it from there. 

Once we are done with Map, we will be ready to wrap the ScriptContext types (for V1, V2 and V3) in AsData, which will significantly speed up scripts that only access a small portion of the script context.

**Comment by uhbif19** [comment]
Cannot `asData` encode "regular" lists with built-in lists as well? It seems like it should be always more performant this way.

**Comment by ana-pantilie** [comment]
@uhbif19 The SOP list type _is_ encoded as a builtin list in its data representation: https://github.com/IntersectMBO/plutus/blob/7b70ab0dfa8cbc3acc3ae6c506adb1ceac5431ac/plutus-tx/src/PlutusTx/IsData/Class.hs#L97

Does this answer your question or did I misunderstand?

**Comment by uhbif19** [comment]
@ana-pantilie 

You right, I formulate my question incorrectly.

This issue implements AssocMap `encoded in BuiltinData`. That way one can use AssocMap in `asData` datatypes. For same reason one needs List `encoded in BuiltinData`, to use lists in `asData` datatypes. Is that not correct?
