### ISSUE TITLE
Fix plutus-metatheory-site nix build script.

### ISSUE THREAD

**Issue by ramsay-t** [IntersectMBO/plutus#5933]
The command `nix build .#plutus-metatheory-site` should convert all the Literate Agda into HTML. There is a script in `nix/plutus-metatheory-site.nix` that partly works but I have a few problems:

1. It caches the Agda phase, which sounds good but it doesn't appear to re-run when I edit one or two of the Agda files. This might not be an issue for most people who don't want to re-run Agda every time they rebuild everything, but in my case I am editing the Agda and need to see the changes in a live, hyperlinked document
2. The jekyll command doesn't seem to index all of the files. The index works and many of the links from there work, but I have found several modules that seem to exist as `.md` but they don't get converted to html. I'm not sure if jekyll is only descending one level, or if it is based of a list somewhere? `Scoped` is an example - it is linked from index.html but doesn't get built.

**Comment by zeme-wana** [comment]
Addressed by https://github.com/IntersectMBO/plutus/pull/5959
