### ISSUE TITLE
Figure out and document the shrinking order on types in the PIR type generator

### ISSUE THREAD

**Issue by zliu41** [IntersectMBO/plutus#5979]
Currently the shrinking order on types isn’t specified anywhere in the PIR generators making it extremely hard to:

1. verify that the shrinker does the right thing and can’t end up being stuck in a loop
2. change literally anything in the shrinker (because it’s hard to tell what implicit invariant a change might break)

We need to fix that by figuring out the shrinking order, documenting it and ensuring that existing code complies with it.

From https://input-output.atlassian.net/browse/PLT-831

**Comment by effectfully** [comment]
Closing in favor of https://github.com/IntersectMBO/plutus/issues/6531.
