### ISSUE TITLE
Investigate if making `fixKind` return a list of types is feasible and worth it

### ISSUE THREAD

**Issue by zliu41** [IntersectMBO/plutus#5980]
Currently `fixKind` returns only one type. Meaning the shrinker always chooses, say, a single particular type variable when fixing the kind of another type variable. It would be nice if it could look at all suitable type variables. This ticket is for investigating if it’s hard to arrange that and if its' beneficial to do so.

Extricated from https://input-output.atlassian.net/browse/PLT-874

**Comment by effectfully** [comment]
Closing in favor of https://github.com/IntersectMBO/plutus/issues/6531.
