### ISSUE TITLE
Obtain an S3 bucket

### ISSUE THREAD

**Issue by zliu41** [IntersectMBO/plutus#5984]
We have a job that extracts and dumps Plutus scripts from mainnet. We used to use a MinIO box provided by Moritz, but it is no longer accessible (and it’s supposed to be a temporary solution in the first place). We should obtain an actual S3 buckets for us to store the script dumps, among other things.

A/C:

- Follow the instructions in https://github.com/input-output-hk/sc-dev-platform/blob/main/doc/kubevela-definitions/s3.md to get an S3 bucket allocated. Reach out to Shea Levy for help if needed.

Extricated from https://input-output.atlassian.net/browse/PLT-9689

**Comment by zliu41** [comment]
Anita Jovic 
April 23, 2024 at 4:15 PM

We first need the AWS


Delete


Lorenzo Calegari 
April 4, 2024 at 5:00 PM

Yes, we are going to sort this all out at the meeting on Monday, hopefully 🤞


Delete

:thumbsup:
1


Anita Jovic 
April 4, 2024 at 4:33 PM

Judith Lochuack and Lorenzo Calegari tagging you for information. We need a direction moving forward so we can unblock this work item. Thank you.


Delete


Yuriy Lazaryev 
April 4, 2024 at 10:07 AM

I have discussed this issue with Shea Levy and learned the following:

Currently, sc-dev-platform has no maintainer and it isn’t clear if there going to be one.

Shea advises our team to acquire own AWS account to manage our deployments independently.

According to Anita Jovic there going to be a meeting on this matter soon, so I mark this task as “Blocked” until we have more clarity.

**Comment by robpangilinanioi** [comment]
For renaming @zeme-wana

**Comment by robpangilinanioi** [comment]
Not needed anymore as per @zeme-wana
