### ISSUE TITLE
Decide what to do with the script dump job

### ISSUE THREAD

**Issue by zliu41** [IntersectMBO/plutus#5985]
The script dump job is in the plutus-apps repo, branch dump-1.35.4: https://github.com/IntersectMBO/plutus-apps/tree/zliu41/dump-1.35.4/plutus-script-evaluation-test

It will stop working after the Conway HF since it runs node 1.35.4. The MinIO storage (https://s3.devx.iog.io) has also stopped working.

We should either update it to depend on node-9.x (and move it out of the plutus-apps repo), or migrate it to use a chain indexer. We originally planned to migrate it to Marconi, but Marconi is no longer being maintained, so we should look for another indexer, perhaps DbSync.

Extricated from https://input-output.atlassian.net/browse/PLT-9668

**Comment by Unisay** [comment]
Dump job updated and moved to a separate repo https://github.com/IntersectMBO/plutus-script-evaluation
