### ISSUE TITLE
See if we can compile data instances

### ISSUE THREAD

**Issue by zliu41** [IntersectMBO/plutus#5990]
It is reported in https://github.com/IntersectMBO/plutus/issues/5768  that using data families leads to the “Irreducible type family application” error. We may be able to compile data instances by ignoring data family declarations. It’s worth checking if it can be made to work.

Extricated from https://input-output.atlassian.net/browse/PLT-9514

**Comment by effectfully** [comment]
I don't understand why we need this issue. And the one that it refers to is basically the same? And is closed?

**Comment by effectfully** [comment]
I'm concluding that this issue is not needed, since it's just a GitHub issue ported to Jira ported back to GitHub, hence I'm closing it.
