### ISSUE TITLE
Migrate closed Jira tickets

### ISSUE THREAD

**Issue by zliu41** [IntersectMBO/plutus#6002]
Closed Jira tickets should be migrated to somewhere private, such as a private repo. Automation would be necessary since there are too many of them.

**Comment by ana-pantilie** [comment]
Blocked on actually having a private repo (which only the core team can access).

**Comment by robpangilinanioi** [comment]
Github issues you can create per hour.  Need to manage and restart the job.

**Comment by zeme-wana** [comment]
Implemented by https://github.com/IntersectMBO/plutus-private/pull/83
