### ISSUE TITLE
Write a CIP for builtin Map/Array

### ISSUE THREAD

**Issue by zliu41** [IntersectMBO/plutus#6003]
Michael has written a draft [here](https://docs.google.com/document/d/1I2hXPXepWMZboKGRRC-MVNi41F16D7aOP47-JW1Jq-w). Polish and publish it as a CIP. [Here](https://docs.google.com/document/d/1TaBXqVVytQSSgFeEcFN39SYJ6m-K9pgWP67ZROtOtwA) is an earlier doc on this subject.

**Comment by effectfully** [comment]
This is now done:

- https://github.com/cardano-foundation/CIPs/pull/915
- https://github.com/cardano-foundation/CIPs/pull/921
