### ISSUE TITLE
Adapt Behavioural proof CK-CEK  to SOPs in the metatheory

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6106]

**Comment by effectfully** [comment]
@ramsay-t do you happen to know the status of this issue?

**Comment by ramsay-t** [comment]
@effectfully these were JIRA issues migrated to GitHub. I think they are "tech debt" things where we just need to update a couple of proofs after the addition of the Sum-Of-Products stuff (before I joined)? I will look into them as I get into the CEK machine stuff in the next PI.

**Comment by effectfully** [comment]
(sorry about accidental closing, got a bit too excited)

**Comment by effectfully** [comment]
@ramsay-t any updates on this one?
