### ISSUE TITLE
Debugging scripts in PLC

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6117]
As a script author, I want to be able to debug my programs so I can find out why they fail.

AC:

Can use some tool to step through a script execution

Can interpret the state at any point during debugging

Can map locations in debugging to original source

Can identify reasons for failure

- [ ] https://github.com/IntersectMBO/plutus/issues/6115
- [ ] https://github.com/IntersectMBO/plutus/issues/6116

**Comment by effectfully** [comment]
We now have a debugger. #6116 isn't closed, but there isn't much point in keeping an Epic around when it just refers to a single open issue, so I'm closing this one.
