### ISSUE TITLE
The PIR typechecker should not depend on the compiler

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6123]
It compiles datatype definitions in order to get the types of the components of the definition. This is a layering violation at best.

We should pull out whatever logic is needed to compute the types of these bits into somewhere common and use it in both places.

e.g. here https://github.com/input-output-hk/plutus/blob/master/plutus-core/plutus-ir/src/PlutusIR/TypeCheck/Internal.hs#L393

### Acceptance criteria
The typechecker does not depend on the compiler!

**Comment by effectfully** [comment]
I agree that the type checker shouldn't depend on the compiler. Is that refactoring worth the effort though? I very much doubt so, hence I'm closing the issue. If anybody disagrees, do feel free to reopen.
