### ISSUE TITLE
Useful generators for PLC and PIR to use in tests and get better coverage

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6125]
- [ ] https://github.com/IntersectMBO/plutus/issues/6126
- [ ] https://github.com/IntersectMBO/plutus/issues/6127
- [ ] https://github.com/IntersectMBO/plutus/issues/6128
- [ ] https://github.com/IntersectMBO/plutus/issues/6129

**Comment by effectfully** [comment]
I don't find the existence of this issue helpful, so I'm closing it. Feel free to reopen if you disagree. Also we can just use labels instead of opening such issues, so maybe we should discuss that.
