### ISSUE TITLE
Develop a strategy for using Neat generator to test equivalence between Agda model and Plutus evaluator

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6126]
As a Plutus developer 

I want to understand the testing strategy being used for comparing the Plutus evaluator with the Agda reference model.

So that I can check that the Neat implementation is correct.

- [ ] Writeup of how we are using the NEAT tests
- [ ] proposal for how to move forward
- [ ] description of our strategy for coverage

**Comment by effectfully** [comment]
I don't believe NEAT tests deserve their own issues given their relative unimportance, so I [merged](https://github.com/IntersectMBO/plutus/issues/6075#issuecomment-2177246302) this one into #6075.
