### ISSUE TITLE
Make coverage reports easily accessible to developers

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6131]
As a Plutus Core developer I want to have easy access to coverage reports so I know if I need to improve the coverage on a PR.

### Acceptance criteria

- Coverage reports for a PR can easily be accessed by the developer making the PR.

- Coverage reports can easily be generated by developers locally.

**Comment by effectfully** [comment]
I doubt this is ever going to happen, but if anybody disagrees do feel free to reopen.
