### ISSUE TITLE
Set up CI to block changes that decrease critical coverage metrics

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6132]
As a Plutus Core developer, I want to be told if key coverage metrics decrease, so that I keep the code well tested.

Key coverage metrics:

- CEK machine coverage by conformance test suite (most important by far)

- others?

Acceptance criteria

- There is a gate in CI that blocks PRs if the key coverage metrics decrease.

**Comment by effectfully** [comment]
I doubt this is ever going to happen and we don't even seem to be evolving the conformance test suite, so I'm closing this issue and if anybody disagrees do feel free to reopen.
