### ISSUE TITLE
Code coverage improvements

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6134]
As a Plutus Core developer I want to have code coverage reports so I know if I have tested my code adequately.

Acceptance criteria
Coverage reports for our test suites are automatically generated

(Maybe?) CI is set up to fail if certain coverage metrics decrease

- [x] https://github.com/IntersectMBO/plutus/issues/6131
- [x] https://github.com/IntersectMBO/plutus/issues/6132
- [ ] https://github.com/IntersectMBO/plutus/issues/6133

**Comment by effectfully** [comment]
This now just refers to the single open issue, so we can as well only have that issue open and close this one.

**Comment by ana-pantilie** [comment]
Thank you for cleaning this up @effectfully !
