### ISSUE TITLE
(OLD, check if outdated) Add a "prettyprintable" constraint alias for terms

### ISSUE THREAD

**Issue by ana-pantilie** [IntersectMBO/plutus#6136]
As it is you have to stitch together a combination of `GShow uni` `Everywhere uni Show` etc, it's fairly annoying. We do this a lot, it would be handy to have an alias exported.

**Comment by effectfully** [comment]
I've done some of that in #5304 and we've had `PrettyClassic`/`PrettyReadable`/`PrettyPlc` since forever, so I'm going to claim that this is done. If somebody disagrees and have concrete improvement ideas, do reopen the issue.
