### ISSUE TITLE
Missing Documentation per OSC Governance

### ISSUE THREAD

**Issue by Ranchhand87** [IntersectMBO/plutus#6241]
The following Required docs are missing and should show on the Main page of Code: CODEOWNERS, CHANGELOG.md
If there are CHANGELOG's please create a top level file and link accordingly.

For Reference: https://intersect.gitbook.io/open-source-committee/policies/governance
Also see Documentation and Legal

**Comment by effectfully** [comment]
Thank you for reporting the issue!

@MattChain volunteered to take care of this, but I cannot add him as an assignee for some reason, so I've added myself for the time being. @MattChain please still do all the work, I'm only going to take credit for it!

**Comment by effectfully** [comment]
@mattchain any progress on this issue?

**Comment by marshada** [comment]
Hi @Ranchhand87 could you please point to the area of the documentation that says the above are required and what specifically is being asked? I don't see it. thanks!

**Comment by Ranchhand87** [comment]
https://intersect.gitbook.io/open-source-committee/policies/documentation#:~:text=CODE_OF_CONDUCT-,A,per%20package%20may%20be%20more%20appropriate),-The%20documents%20should
Here is the link regarding the Changelog, Please ensure that one shows on the Top level for ease of understanding. Again the top level can links to any changelog that is already in place. 
CODEOWNERS  is a general requirement and reinforces those that are primarily responsible for writing and maintaining code within this repo. Although this may be in the ReadMe. This is a standard across the other core repos.

**Comment by Ranchhand87** [comment]
Please provide an update. Thank you.

**Comment by effectfully** [comment]
@marshada is on long-term leave, so probably not gonna take care of this.

@zliu41 it looks like somebody else should get this ticket?

**Comment by zliu41** [comment]
Several team members are on PTO, and we have a team meetup the week of Aug 26. We can aim to tackle this in early September.

**Comment by Ranchhand87** [comment]
Closing this issue as it has been renewed with a more specific tasking #6423
