### ISSUE TITLE
V3 script size increased in 1.30

### ISSUE THREAD

**Issue by Unisay** [IntersectMBO/plutus#6242]
@mgmeier :

So this snippet is now the scaffolding for our V3 benchmarking scripts (validtor, spending script) - we only need the redeemer

```haskell
mkValidator :: BuiltinData -> BuiltinUnit
mkValidator arg =
  [...]
  where
    PlutusV3.ScriptContext _txInfo (PlutusV3.Redeemer redeemer) _scriptInfo
      = PlutusV3.unsafeFromBuiltinData arg
```

Now, when submitting transactions as opposed to before CIP-69, for the same script, the tx size increases from 968 bytes to 3401 bytes, which is a size increase by ~350%.
-  With CIP-69, is there a way to unwrap the redeemer that is more efficient wrt. to size of serialized code?
-  In general, is some sort of unwrapping code inside a script now a requirement?

Add: in our benchmarking setup, for the `HashOntoG2AndAdd` benchmark, this correlates with a tx fee increase by ~21%. (edited)

This task is to investigate such a size increase and conclude if this is expected and justified or if something fishy is going on.

**Comment by effectfully** [comment]
This seems to be expected behavior, see [this](https://github.com/IntersectMBO/plutus/issues/6151#issuecomment-2142983526) comment.

**Comment by Unisay** [comment]
[Here is the Spec ](https://github.com/IntersectMBO/plutus/pull/6247)which shows:
- that V3 script size has increased after adopting CIP-117 
- a way to avoid size increase by decoding redeemer and datum in a lazy fashion.
