### ISSUE TITLE
No instance for ‘PlutusTx.Eq.Eq ScriptPurpose’  arising from a use of ‘lookup’

### ISSUE THREAD

**Issue by zlonast** [IntersectMBO/plutus#6273]
### Summary

Сan you tell me where I'm wrong in my wishes?
I want to do `lookup (Rewarding sc) (txInfoRedeemers $ scriptContextTxInfo ctx)`, but in [pr 6173](https://github.com/IntersectMBO/plutus/pull/6173) delete instance for `PlutusTx.Eq.Eq ScriptPurpose` 

### Steps to reproduce the behavior

add line to plutuscript `lookup (Rewarding $ ScriptCredential $ ScriptHash hash) (txInfoRedeemers $ scriptContextTxInfo ctx)`

### Actual Result

error

### Expected Result

no errors

### Describe the approach you would take to fix this

Bring back the behavior that was there before?

### System info

os: Ubuntu 22.04.3
plutus-core: 1.30

**Comment by effectfully** [comment]
@ana-pantilie you're probably equipped best to answer this one.

**Comment by zlonast** [comment]
Do I understand correctly that you are suggesting something like that? @ana-pantilie
```
{-# INLINABLE eqCredential #-}
eqCredential :: Credential -> ScriptPurpose -> Bool
eqCredential a (Rewarding b) = a PlutusTx.== b
eqCredential _ _ = Haskell.False
```

```
find (eqCredential sc) (keys $ txInfoRedeemers $ scriptContextTxInfo ctx)
```

**Comment by ana-pantilie** [comment]
@zlonast yes that's what I was thinking of.

**Comment by colll78** [comment]
```
instance PlutusTx.Eq.Eq ScriptPurpose where 
  (==) a b = PlutusTx.toBuiltinData a == PlutusTx.toBuiltinData b
```
