### ISSUE TITLE
Decide the fate of plutus-ghc-stub

### ISSUE THREAD

**Issue by bezirg** [IntersectMBO/plutus#6355]
From what I gathered from reading git logs:

plutus-ghc-stub package was created to allow cross-compiling to windows. 
It provides a "stub" interface to ghc, mimicking ghc 8.6.

Since we have long moved to newer ghc versions, we have not updated that stub to match the newer ghc version interface.
Hence, the disablement of building plutus-tx-plugin-dependent packages when windows cross-compiling:

https://github.com/IntersectMBO/plutus/pull/4911

This makes the plutus-ghc-stub in its current situation utterly redundant.
Decide 1 of the 2:

A. Remove plutus-ghc-stub and continue not supporting windows cross-compiling for plutus-tx-plugin-dependants
B. Port/update plutus-ghc-stub to our target dev ghc version (currently: 9.6)

@hamishmack @zeme-wana

**Comment by zeme-wana** [comment]
I'm not sure there is much demand for compiling plutus on Windows for ghc versions other than the current default (i.e. 9.6), so I would go for (A) which is obviously the easier option.
It's unclear to me how much effort would be required for (B)
