### ISSUE TITLE
Minting with PlutusV3 seems to be broken

### ISSUE THREAD

**Issue by ajuggler** [IntersectMBO/plutus#6419]
### Summary

It seems to be impossible to mint with a PlutusV3 script.  A simple "always succeeds" minting script fails with message
```
The Plutus script evaluation failed: The evaluation finished but the result value is not valid. Plutus V3 scripts must return BuiltinUnit. Returning any other value is considered a failure.
```

### Steps to reproduce the behavior

Clone repository https://github.com/ajuggler/simple-minting.git and follow the few instructions.

### Actual Result

Attempt to build transaction with cardano-cli produces error:
```
Command failed: transaction build  Error: The following scripts have execution failures:
the script for policyId 0 (in ascending order of the PolicyIds) failed with: 
The Plutus script evaluation failed: The evaluation finished but the result value is not valid. Plutus V3 scripts must return BuiltinUnit. Returning any other value is considered a failure.
```

### Expected Result

Successful build and submission of minting Tx was expected.

### System info

OS: Debian GNU/Linux 11
Version: Linux 5.10.0-18-arm64
Plutus Version:  1.31

**Comment by effectfully** [comment]
According to the [docs](https://plutus.cardano.intersectmbo.org/docs/working-with-scripts/ledger-language-version#plutus-v3):

> all Plutus V3 scripts should have the following type in Plutus Tx:
> ```haskell
> BuiltinData -> BuiltinUnit
> ```

and you have a `BuiltinData -> BuiltinData -> BuiltinUnit` in there.

**Comment by effectfully** [comment]
... does that answer your question?

**Comment by ajuggler** [comment]
Yes indeed, thank you very much.  Now script works as expected.
