### ISSUE TITLE
Ensure the plutus-tx-template repo aligns with the OSC documentation policy

### ISSUE THREAD

**Issue by zliu41** [IntersectMBO/plutus#6423]
See https://intersect.gitbook.io/open-source-committee/policies/documentation and https://intersect.gitbook.io/open-source-committee/policies/governance

**Comment by Ranchhand87** [comment]
Please also ensure that this Plutus repo is updated to the same standard. Ref #6241

**Comment by robpangilinanioi** [comment]
Need additional feedback from @zliu41 .  @ana-pantilie already provided feedback.

**Comment by Ranchhand87** [comment]
@zeme-wana @zliu41 @ana-pantilie  Update for Security Policy - Posting here to avoid a new issue.

New Governance Metric - OSC Governance/Security TWG

Per the Security TWG: Please update/add Security.md

Please refer to: https://github.com/IntersectMBO/Open-Source-Office/blob/main/SECURITY.md

The initial deadline for these changes to be made is 30 September 2024. Thank you.

**Comment by zeme-wana** [comment]
@Ranchhand87 both plutus and plutus-tx-template already contain a SECURITY.md file with the expected contents. Can you confirm please?
