### ISSUE TITLE
The error trace logs are ignored in compiled contract

### ISSUE THREAD

**Issue by mesudip** [IntersectMBO/plutus#6511]
### Summary

It appears that plutus compiler removes the logs for optimization in compiled contract. 
It is evident from the use of `check'` function instead of builitin `check` with same code.

### Case 1:
```
check' :: Bool -> BuiltinUnit
check' b = if b then BI.unitval else traceError "MINT5"

{-# INLINEABLE mintValidator #-}
mintValidator :: TxOutRef -> CurrencySymbol ->  Value ->  BuiltinUnit
mintValidator nftOutRef ownCS  mint =
  check' ...
```
#### Message
```
CekError : An error has occurred:\nThe machine terminated because of an error, 
  either from a built-in function or from an explicit use of 'error'. : []
```

### Case 2:
```
{-# INLINEABLE mintValidator #-}
mintValidator' :: TxOutRef -> CurrencySymbol ->  Value ->  BuiltinUnit
mintValidator' nftOutRef ownCS mint =
  check ...
```
#### Message
```
CekError : An error has occurred:\nThe machine terminated because of an error, 
  either from a built-in function or from an explicit use of 'error'. : [\"PT5\"]
```

### Expected Result

`check'` should also show the `Cek` error with the  `MINT5 ` text when evaluating.

### Describe the approach you would take to fix this

Have a way to enable the trace logging somewhere

**Comment by zliu41** [comment]
Hi @mesudip, have a look at [this](https://plutus.cardano.intersectmbo.org/docs/troubleshooting#missing-trace-messages) and see if it helps.

**Comment by effectfully** [comment]
> Hi @mesudip, have a look at [this](https://plutus.cardano.intersectmbo.org/docs/troubleshooting#missing-trace-messages) and see if it helps.

It really should, so I'm closing the issue, given that it's been two weeks. If the fix doesn't help, please reopen the issue, we'll look into it further.
