### ISSUE TITLE
Missing positive conformance test cases for some Plutus V3 builtins 

### ISSUE THREAD

**Issue by sierkov** [IntersectMBO/plutus#6553]
### Summary

When running the ```plutus-conformance``` test cases on a [C++ implementation of the Plutus machine](https://github.com/sierkov/daedalus-turbo/tree/main/lib/dt/plutus), we found that some builtins do not have positive test cases. Because of that even a dummy “fail everytime” implementation can pass the tests.

For example, these builtins do not have positive test cases:
- verifyEcdsaSecp256k1Signature
- verifySchnorrSecp256k1Signature

### Steps to reproduce the behavior

For verifyEcdsaSecp256k1Signature builtin
1. Open ```plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifyEcdsaSecp256k1Signature``` directory.
2. List the contents of all *.uplc.expected files.

For verifySchnorrSecp256k1Signature builtin
1. Open ```plutus-conformance/test-cases/uplc/evaluation/builtin/semantics/verifySchnorrSecp256k1Signature``` directory.
2. List the contents of all *.uplc.expected files.

### Actual Result

All *.uplc.expected files contain only "evaluation failure" text.

### Expected Result

The *.uplc.expected files of the test cases contain both "evaluation failure" text and succesful verification examples.

### Describe the approach you would take to fix this

Import a minimal set of test vectors from the relevant cryptographic library.

**Comment by effectfully** [comment]
@kwxm it sounds like it wouldn't be hard to add a few positive tests to the conformance test suite for those builtins?

**Comment by kwxm** [comment]
@sierkov Thanks for pointing this out.  We've added some more tests in PRs #6617 and #6622 which I hope will be a bit more comprehensive.

**Comment by sierkov** [comment]
@kwxm, looks great. Thank you!
