### ISSUE TITLE
`BuiltingByteString` construction using `[Word8]`

### ISSUE THREAD

**Issue by Unisay** [IntersectMBO/plutus#6670]
### Describe the feature you'd like

Plinth function:
```haskell
builtinByteStringFromBytes :: [Haskell.Word8] -> BuiltinByteString
```

### Describe alternatives you've considered

Alternative ways that already exist:
```haskell
builtinByteStringFromString :: Haskell.String -> BuiltinByteString
```

UPD:
```haskell
{-# LANGUAGE NumericUnderscores #-}
integerToByteString BigEndian 4 0x_DE_AD_BE_EF
```

**Comment by colll78** [comment]
This is a huge QOL improvement!

**Comment by Unisay** [comment]
It has been discovered, that GHC Core for `[Haskell.Word8]` looks like this (Scott-encoded list):
```haskell
build
  @Word8
  (\ (@a_dmtK)
     (c_dmtL [OS=OneShot] :: Word8 -> a_dmtK -> a_dmtK)
     (n_dmtM [Occ=Once1, OS=OneShot] :: a_dmtK) ->
     c_dmtL
       (src<test/BuiltinByteString/Spec.hs:134:9-68>
        $fNumWord8_$cfromInteger (IS 190#))
       (c_dmtL
          (src<test/BuiltinByteString/Spec.hs:134:9-68>
           $fNumWord8_$cfromInteger (IS 239#))
          (c_dmtL
             (src<test/BuiltinByteString/Spec.hs:134:9-68>
              $fNumWord8_$cfromInteger (IS 0#))
             (c_dmtL
                (src<test/BuiltinByteString/Spec.hs:134:9-68>
                 $fNumWord8_$cfromInteger (IS 255#))
                n_dmtM))))
```
while it is possible to process such AST in compile time extracting individual bytes, we have decided not to pursue the original goal to have a list-based construction syntax. Instead we propose to use alternative methods (integer and string literals with bytes encoded in them). Taking for example a use-case with a byte string used as a lookup table for powers of 2 one can encode it using `IsString` instance: `"\1\2\3\8\16\32\128".`
