### ISSUE TITLE
Expose `index-envs` as public library

### ISSUE THREAD

**Issue by SeungheonOh** [IntersectMBO/plutus#6675]
### Describe the feature you'd like

Some of the functions in `UntypedPlutusCore.Evaluation.Machine.SteppableCek.Internal` virtually pointless since it's require `RAList` values which is not exposed to public from `index-envs` library. It would be nice to have `index-envs` as a public library so downstream library can access CEK machine internals.

**Comment by effectfully** [comment]
Sure, we can expose it, although the API is probably going to change, because I'm changing how this stuff is used in the CEK machine as we speak. Wanna create a PR?

**Comment by SeungheonOh** [comment]
PR is already there
